services:
  - type: web
    name: sise-enedis
    env: python
    plan: free
    region: frankfurt  # ou oregon / singapore selon ta localisation
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Scripts/app/main.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    # Si tu veux ignorer certaines branches (ex: ne déployer que "dev" ou "main") :
    branch: new_departement   # à changer plus tard vers main quand tu seras prêt
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
