services:
  - type: web
    name: sise-enedis
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y git-lfs
      git lfs install
      git lfs pull
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run Scripts/app/main.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    branch: new_departement
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
